sudo: false
language: python
python:
- '3.5'
before_install:
- pip install -r requirements.txt
- pip install -e .
script: pytest -m "not compiled" --cov=pythonwhat
after_success: codecov --token=$CODECOV_TOKEN
deploy:
  provider: pypi
  user: datacamp
  password:
    secure: oyhm/R427TtmjJFMlvxQAR3UK5CA3vRSQd7CTtGTkL3W2zoZsPI7p3XbJn4CwC1f1XPdAbfN/Km035Fn4NlVHwJT54NTGkcy8GPV8whxEvWptiA1XWO6uwIqHh7rF/cVhX21AYXWAYkFq0Y0w1+q3OK75czMBrclwn9t+m111uoEUdZyowI5EVXbTHfzpNrRY3wA+tVWdz3Yd4IIC5foFsMP28j/5JCuMWXT1Knf53ZaoTSpyoEllAe/8sP/3K6/adgiwz5vL6kTFtSeuX0EQ6uvlXWyP4x8APNcnfVKxEC16iwakOgVzhw4n3uMsQ6tgo11w+A2crJU1N8KxdZtG8gAw42jWSZMmB3SHHx0NQhi71SvrjYXwDwe8bOvRFDHiR+2WQzoYC4WJUyn4WYpScazkQpeqYdoOTBnAr1VNzZHOQNwejX5KpLP15oXj6ima/lqefQWnIRixeBkJibSTdRl2HlvdPzP75DSjg8eA0Xt8/ad2oWV4om9zIUwAkJrnzih3ZsnshSqVZcxpsRDZvV2LXz39JzlNECqxfLGF+Oy6M8QQXnALzYuHhs/BgzPlLdQw8QLwHPqvv38LNfrWo36jR3j9UYu1/45LZauIEJuLGCyPclT1PDnAtxH3SGCEi8aAODzAi2qptbBHxJHjsRcVeMx6Oiz4AmEuxT4QRU=
  distributions: sdist bdist_wheel
  on:
    tags: true
    repo: datacamp/pythonwhat
  skip_upload_docs: true
