sudo: false
language: python
python:
- '3.9'
before_install:
- pip3.9 install -r requirements.txt
- pip3.9 install -e .
script: pytest -m "not compiled" --cov=pythonwhat
deploy:
  provider: pypi
  user: datacamp
  password:
    secure: JrQnpSi03zbBXpRPYydm1K3539UYsn8tefJtWOm6mnoSl0/zeFU7s5vsVCu5LngmM3O1GzpfVQCh9BUC/1u+oDr7NpQ6zASBbNkwyb9sWj2eH/6fOBkLPhOIBspBTDr+LYOAvZC4+fr/7tb7OtiMzTKeAlRJRkj1LUmEbD8sbBdn5msDfY14AmhtTfA4MibsBlF3uzIDgpy4HaIJRw/YgZXcasB83Mxv5g242FHrCNUmbWJkaiSb+CRwcLqpCYg5B1hNLKA61IBi4Cpk6iM2XsP0LTk+TmS6hPZi3Qbdm6knkhhElbmKyXvANFrswrd4HbR8tRMBcOR/APlLqdVm6aKXF0E20rkcpVEdseSssJ/O+q0EiRe3033nupNseLNmQcQdGeOAoOIOkcKMySrM4eUK2XjZ4M+Uw9arZ+creMiIhzMYOoMnCrkXlyQkyz5X2qDW+HyTgl0aLUaOKGNaoJ7UJ78sGihx34tFaxI9sB6InZ3wF/lj1KbvQG66gMjIRVZ20AqLKWvUYCED6DzgPQ+T5IVG4GDezUSV8J/XZGDUnkN1z0zeQZo3UTinicriRzYgpzYhs4iZ1fXo4pw26xk69SQZauxr5jYrTWTygKvyPK6Qnpq7e4EXGYDQHNVevyYFic/kAvP+Aofly/38iK59AjBiKGeUr7SYTdag9N4=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: datacamp/pythonwhat
  skip_upload_docs: true
